global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Security.Claims;
global using DataCURD.A01.Shared;
global using DataCURD.A01.Shared.DataHelpers;
global using DataCURD.A02._01.Domain.Models.Application.UsersAndRoles;
global using DataCURD.A02._01.Domain.Models.OrganizationBussiness;
global using DataCURD.A02._02.Domain.ORM;
global using DataCURD.A02._03.Domain.Repositories;
global using DataCURD.A02._03.Domain.Repositories.ForUsersAndRoles;
global using DataCURD.A03._01.Dto.Models;
global using DataCURD.A03._01.Dto.Models.Application.UsersAndRoles;
global using DataCURD.A03._01.Dto.Models.OrganizationBussiness;
global using DataCURD.A03._02.Dto.Services;
global using DataCURD.A03._02.Dto.Services.Helpers;
global using DataCURD.A04._01.Request.Models;
global using DataCURD.A04._01.Request.Models.Application.UsersAndRoles;
global using DataCURD.A04._01.Request.Models.OrganizationBussiness;
global using DataCURD.A04._02.Request.Services;
global using DataCURD.B01.BaseControllers;
global using DataCURD.B03.Helpers;
global using Microsoft.AspNetCore.Authorization;
global using DataCURD.A01.Shared.Authorization;
global using System.Collections.ObjectModel;
global using DataCURD.A04._02.Request.Services.Extenssiones.OrganizationBussiness;
global using DataCURD.B04.Permissions;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Text;
global using DataCURD.A03._02.Dto.Services.ForUsersAndRoles;
global using DataCURD.A04._02.Request.Services.ForUsersAndRoles;



